name: gg_workflow
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aioeasywebdav=2.4.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - amply=0.1.5
  - appdirs=1.4.4
  - async-timeout=4.0.2
  - atk-1.0=2.36.0
  - attmap=0.13.2
  - attrs=22.1.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - bc=1.07.1
  - bcftools=1.14
  - bcrypt=3.2.2
  - boto3=1.24.69
  - botocore=1.27.69
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.6.15
  - cachetools=5.2.0
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - coin-or-cbc=2.10.8
  - coin-or-cgl=0.60.6
  - coin-or-clp=1.17.7
  - coin-or-osi=0.108.7
  - coin-or-utils=2.11.6
  - coincbc=2.10.8
  - commonmark=0.9.1
  - configargparse=1.5.3
  - connection_pool=0.0.3
  - cryptography=37.0.1
  - curl=7.83.1
  - dataclasses=0.8
  - datrie=0.8.2
  - decorator=5.1.1
  - defusedxml=0.7.1
  - docutils=0.19
  - dpath=2.0.6
  - dropbox=11.34.0
  - expat=2.4.8
  - filechunkio=1.8
  - filelock=3.8.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freebayes=1.3.6
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.1
  - ftputil=5.0.4
  - future=0.18.2
  - gdk-pixbuf=2.42.8
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.27
  - glib=2.72.1
  - glib-tools=2.72.1
  - google-api-core=2.10.0
  - google-api-python-client=2.60.0
  - google-auth=2.11.0
  - google-auth-httplib2=0.1.0
  - google-cloud-core=2.3.2
  - google-cloud-storage=2.5.0
  - google-crc32c=1.1.2
  - google-resumable-media=2.3.3
  - googleapis-common-protos=1.56.4
  - graphite2=1.3.13
  - graphviz=5.0.1
  - grpcio=1.46.0
  - gsl=2.7
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=5.1.0
  - htslib=1.14
  - httplib2=0.20.4
  - icu=70.1
  - idna=3.3
  - importlib-metadata=4.11.4
  - importlib_resources=5.9.0
  - iniconfig=1.1.1
  - jinja2=3.1.2
  - jmespath=1.0.1
  - jpeg=9e
  - jsonschema=4.15.0
  - jupyter_core=4.11.1
  - keyutils=1.6.1
  - krb5=1.19.3
  - ld_impl_linux-64=2.36.1
  - lerc=4.0.0
  - libabseil=20220623.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=7.83.1
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgd=2.3.3
  - libgfortran-ng=12.1.0
  - libgfortran5=12.1.0
  - libglib=2.72.1
  - libgomp=12.1.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnghttp2=1.47.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.37
  - libprotobuf=3.21.5
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libsqlite=3.39.3
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - logmuse=0.2.6
  - markupsafe=2.1.1
  - multidict=6.0.2
  - nbformat=5.4.0
  - ncurses=6.3
  - numpy=1.23.2
  - oauth2client=4.1.3
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.4
  - pango=1.50.9
  - parallel=20220722
  - paramiko=2.11.0
  - pcre=8.45
  - peppy=0.35.1
  - perl=5.32.1
  - pip=22.2.2
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - plac=1.3.5
  - pluggy=1.0.0
  - ply=3.11
  - prettytable=3.4.1
  - protobuf=4.21.5
  - psutil=5.9.2
  - pthread-stubs=0.4
  - pulp=2.6.0
  - py=1.11.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.13.0
  - pynacl=1.5.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyrsistent=0.18.1
  - pysftp=0.2.9
  - pysocks=1.7.1
  - pytest=7.1.3
  - python=3.10.6
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.1
  - python-irodsclient=1.1.4
  - python_abi=3.10
  - pytz=2022.2.1
  - pyu2f=0.1.5
  - pyyaml=6.0
  - ratelimiter=1.2.0
  - re2=2022.06.01
  - readline=8.1.2
  - requests=2.28.1
  - retry=0.9.2
  - rich=12.5.1
  - rsa=4.9
  - s3transfer=0.6.0
  - samtools=1.6
  - setuptools=65.3.0
  - setuptools-scm=7.0.5
  - six=1.16.0
  - slacker=0.14.0
  - smart_open=6.1.0
  - smmap=3.0.5
  - snakemake=7.13.0
  - snakemake-minimal=7.13.0
  - stone=3.3.1
  - stopit=1.1.2
  - tabixpp=1.1.0
  - tabulate=0.8.10
  - tk=8.6.12
  - tomli=2.0.1
  - toposort=1.7
  - traitlets=5.3.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - ubiquerg=0.6.2
  - uritemplate=4.1.1
  - urllib3=1.26.11
  - vcflib=1.0.3
  - vcftools=0.1.16
  - veracitools=0.1.3
  - vg=1.42.0
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wrapt=1.14.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.7.2
  - yte=1.5.1
  - zipp=3.8.1
  - zlib=1.2.12
  - zstd=1.5.2

